apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "logstronaut.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage