apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: kube-prometheus-stack
  labels:
    serviceMonitorSelector: prometheus
    release: prometheus
  name: {{ include "logstronaut.fullname" . }}-svc-monit
spec:
  endpoints:
  - interval: 30s
    targetPort: {{ .Values.service.port }}
    path: /metrics
  selector:
    matchLabels:
      app: {{ include "logstronaut.fullname" . }}