apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: {{ include "logstronaut.fullname" . }}-svc-monit
spec:
  endpoints:
  - interval: 30s
    targetPort: {{ .Values.service.port }}
    path: /metrics
  selector:
    matchNames:
    - {{ include "logstronaut.fullname" . }}