// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: message.sql

package db

import (
	"context"
)

const storeMessage = `-- name: StoreMessage :one
INSERT INTO messages (
  message_content
) VALUES (
  $1
) RETURNING id, message_content
`

func (q *Queries) StoreMessage(ctx context.Context, messageContent string) (Message, error) {
	row := q.db.QueryRowContext(ctx, storeMessage, messageContent)
	var i Message
	err := row.Scan(&i.ID, &i.MessageContent)
	return i, err
}
