// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Message struct {
	ID             int64  `json:"id"`
	MessageContent string `json:"message_content"`
}
