// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	StoreMessage(ctx context.Context, messageContent string) (Message, error)
}

var _ Querier = (*Queries)(nil)
